CREATE TABLE `weather` (
  `ID`          INT(11)       NOT NULL AUTO_INCREMENT,
  `time`        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `temperature` DECIMAL(5, 2) NOT NULL,
  `humidity`    DECIMAL(5, 2) NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =InnoDB
  AUTO_INCREMENT =4
  DEFAULT CHARSET =utf8;
